namespace Itmo.ObjectOrientedProgramming.Lab2.Models.ProcessorCoolingSystem;

public interface IProcessorCoolingSystemBuilderDirect
{
    IProcessorCoolingSystemBuilder Direct(IProcessorCoolingSystemBuilder processorCoolingSystemBuilder);
}